# This is a basic workflow to help you get started with Actions

name: Mod Deployment

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: windows-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      # Runs a single command using the runners shell
      - name: Compress the mod to zip
        run: |
          $compress = @{
            Path = "${{ github.workspace }}\locale\", "${{ github.workspace }}\prototypes\",
                   "${{ github.workspace }}\LICENSE", "${{ github.workspace }}\README*",
                   "${{ github.workspace }}\changelog*", "${{ github.workspace }}\*.lua",
                   "${{ github.workspace }}\info.json", "${{ github.workspace }}\thumbnail.png"
            DestinationPath = "${{ github.workspace }}\mod-${{ github.sha }}.zip"
          }
          Compress-Archive @compress
        shell: pwsh

      # Runs a set of commands using the runners shell
      - name: Upload the zipped mod
        uses: actions/upload-artifact@v3
        with:
          name: "K2RFAC_${{ github.ref_name }}_${{ github.workflow }}_${{ github.event_name }}"
          path: "${{ github.workspace }}/*.zip"
          if-no-files-found: error
          retention-days: 1
